---
kind: pipeline
type: docker
name: default

platform:
  arch: arm64

steps:
- name: test
  image: docker-registry.dev:5000/tesseract:latest
  commands:
  - swift test

trigger:
  paths:
    include:
    - "*.swift"
    - "*.modulemap"
    - ".drone.yml"
  event:
  - pull_request
  - push
  - tag

---
kind: pipeline
type: docker
name: build-image

platform:
  arch: arm64

steps:
- name: docker_publish_dry_run
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: docker/drone.Dockerfile
    registry: docker-registry.dev:5000
    repo: docker-registry.dev:5000/tesseract
    insecure: true

- name: docker_publish
  image: plugins/docker
  settings:
    dockerfile: docker/drone.Dockerfile
    registry: docker-registry.dev:5000
    repo: docker-registry.dev:5000/tesseract
    insecure: true
  when:
    event:
    - tag

trigger:
  paths:
    include:
    - docker/drone.Dockerfile
