name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 11.4
      run: sudo xcode-select --switch /Applications/Xcode_11.4.app/Contents/Developer
    - name: Run tests
      run: fastlane scan
        working-directory: SwiftyTesseract
    - name: Lint Podspec    
      run: fastlane lint_podspec
        working-directory: SwiftyTesseract
